
networks:
  laravel:
    external: true

#volumes:
#  cron_volume:
#  caddy_caddyfile:
#  vue_node_modules:
#  vue_prod_build:


services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - laravel


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - laravel

  mysql_db_master:
    container_name: mysql_db_master
    image: dockerhub.timeweb.cloud/library/mariadb:10.7.8
    networks:
      - laravel
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
    volumes:
      - '${MYSQL_DB_MASTER_FOLDER}:/var/lib/mysql'
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_db_master:db
    ports:
      - 6067:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql_db_master
    networks:
      - laravel

  2503master:
    container_name: 2503master
    depends_on:
      - mysql_db_master
#    links:
#      - mysql_db_master:db_mysql
    networks:
      - laravel
#    expose:
#      - 9000
    build:
      context: .
      dockerfile: docker.2503master.Dockerfile
    working_dir: ${FOLDER_2503MASTER_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_2503MASTER_SERV}
    restart: unless-stopped
    volumes:
      - '${FOLDER_2503MASTER}:${FOLDER_2503MASTER_SERV}'

  2503master-queue:
    container_name: 2503master-queue
    depends_on:
      - 2503master
    links:
      - mysql_db_master:db_mysql
    networks:
      - laravel
    build:
      context: .
      dockerfile: docker.2503master.Dockerfile
    working_dir: ${FOLDER_2503MASTER_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_2503MASTER_SERV}
    restart: unless-stopped
    volumes:
      - '${FOLDER_2503MASTER}:${FOLDER_2503MASTER_SERV}'
    command: >
      sh -c "
        cd ${FOLDER_2503MASTER_SERV} &&
        php artisan queue:work database --queue=default,notifications --sleep=3 --tries=3 --daemon
      "

#  2503master-scheduler:
#    container_name: 2503master-scheduler
#    depends_on:
#      - 2503master
#    networks:
#      - laravel
#    links:
#      - mysql_db_master:db_mysql
#    build:
#      context: .
#      dockerfile: docker.2503master.Dockerfile
#    working_dir: ${FOLDER_2503MASTER_SERV}
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#      - FOLDER=${FOLDER_2503MASTER_SERV}
##    restart: unless-stopped
#    restart: always
#    volumes:
#      - '${FOLDER_2503MASTER}:${FOLDER_2503MASTER_SERV}'
#    command: >
#      sh -c "
#        cd ${FOLDER_2503MASTER_SERV} &&
#        while true; do php artisan schedule:run; sleep 60; done
#      "
#
##    healthcheck:
##      test: ["CMD", "curl", "-k", "-f", "https://stn.local"]
##      interval: 30s
##      timeout: 10s
##      retries: 3
##      start_period: 10s

